site_name: Spectrans Documentation
site_description: Spectral Transformers - Efficient spectral methods for deep learning
site_author: Spectrans Team
site_url: https://github.com/aaronstevenwhite/spectrans

repo_name: spectrans
repo_url: https://github.com/aaronstevenwhite/spectrans
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_source: true
            show_root_heading: false
            show_category_heading: true
            show_if_no_docstring: false
            merge_init_into_class: true
            members_order: source
            separate_signature: true
            line_length: 80
            show_signature_annotations: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference:
      - Overview: api/index.md
      - Transforms: api/transforms.md
      - Kernels: api/kernels.md
      - Layers: api/layers.md
      - Blocks: api/blocks.md
      - Models: api/models.md
      - Utils: api/utils.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aaronstevenwhite/spectrans
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spectrans/
  version:
    provider: mike
    default: stable